# Copyright (c) 2023 RFull Development
# This source code is managed under the MIT license. See LICENSE in the project root.
version: "3.9"
services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    hostname: zipkin
    restart: always
    ports:
      - 9411:9411
